name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  attest-provenance:
    name: Attest provenance GitHub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81
          override: true

      - name: cargo fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch

      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install NPM dependencies
        run: npm ci

      - name: Check build
        run: npm run build

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'build'
